### get user
GET http://localhost:3001/api/users/

### create user
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "fabiospia"
}

### update user
PUT http://localhost:3001/api/users/4
Content-Type: application/json

{
    "username": "desarrolladorweb"
}

### delete user
DELETE http://localhost:3001/api/users/3
Content-Type: application/json

### create user | url encoded
POST http://localhost:3001/api/users/
Content-Type: application/x-www-form-urlencoded

username=desarrolladorfullstack

### test.txt | static resource
GET http://localhost:3001/test.txt

### fibonacci.txt | static resource
GET http://localhost:3000/fibonacci.txt